env:
  EXTNAME: utf8

language: php
php:
  - 7.2
  - 7.3
  - 7.4snapshot
  - nightly

matrix:
  allow_failures:
    - php: nightly

branches:
  only:
  - master
  - travis
  - /^v\d+\.\d+\.\d+$/

install:
  - phpize
  - ./configure
  - make

before_script:
  make install

script:
  make test

after_failure:
  - |
    for FILE in $(find tests -name '*.diff'); do
      echo $FILE
      cat FILE
      echo
    done

before_deploy:
  - pecl package
  - export RELEASE_PACKAGE=$(ls "$EXTNAME"-*.tgz)

deploy:
  provider: releases
  auth_token:
    secure: "ZQtHrGfCkMi9I85e6Ha9rGc9SVf61LK+NJG3LvB2kmrD7OWseM6ou9ehx6I+4z/ZhYldmZmkU3F237wj8d0b/ti0KhokUkSkuF4Ov9vIWvU6UwREGNBJvKdkUdOSnabozOWYn+gLacstrNCmMvHPJ63QTABdFTc4W+9Wr8VWmsh9kyL8yODe7LmOhbZ0Pv/q07rzjZA3NoQ+duLSoG2EyPSGQVjPrWD8balGefzTZpDGac4FX0oBNbEH/SgnJ2FgxxqNTpXrdIIx6snMWaa4yNKxpdZ/jggJx+xCPuNtVc0OfLCyfqrfCKj1DPPaOFcUd3/Fb2esZUYyLGV7wbwGbQhMtPey9ZbvMw2wv1ZMuoJ7Q7/qA8ZmX7AH5ULCIuogyHEIWmcU1gntBEcJoUIohQK9Vhqr7TfKD7eHMf7+YFiVbgTdSQ0cMeuXug2XFRw5eExUk0VuBzQ8SntUBjQal80ygBIAYXeUWqbYIj+/mvdVCahgQu3e50S4klzZRs5nUXd1MWw44vAT+Ka29jOve3yYxz/SIJrpqdQsVvKFZKu1+nueUAWr6T7SCHVGOQASB8s7HMUGGSwa42F/YOkNJ/BscrLOXT9E1JPTMyphso/Vfx/AaTh47/KEgXyPZofIIQYz2R2rjrSIip8NNXU+NZ4wgNmCk5R2+Kwy8uYqCj4="
  file: "$RELEASE_PACKAGE"
  skip_cleanup: true
  name: "$TRAVIS_TAG"
  prerelease: true
  on:
    tags: true
